export const ROTATE_INTERVAL_MS = 10_000;

export const SYMBOLS = [
  {
    id: "btc",
    label: "BTC",
    pair: "USD",
    name: "Bitcoin",
    sourceType: "binance",
    sourceSymbol: "BTCUSDT",
    fallbackCoinId: "bitcoin",
    sourceTag: "Binance",
  },
  {
    id: "eth",
    label: "ETH",
    pair: "USD",
    name: "Ethereum",
    sourceType: "binance",
    sourceSymbol: "ETHUSDT",
    fallbackCoinId: "ethereum",
    sourceTag: "Binance",
  },
  {
    id: "xauusd",
    label: "XAU",
    pair: "USD",
    name: "London Gold",
    sourceType: "yahoo_proxy",
    sourceSymbol: "GC=F",
    sourceTag: "Yahoo(Proxy)",
    demoSource: true,
  },
  {
    id: "spx",
    label: "SPX",
    pair: "USD",
    name: "S&P 500",
    sourceType: "yahoo_proxy",
    sourceSymbol: "^GSPC",
    sourceTag: "Yahoo(Proxy)",
    demoSource: true,
  },
  {
    id: "ndx",
    label: "NDX",
    pair: "USD",
    name: "NASDAQ 100",
    sourceType: "yahoo_proxy",
    sourceSymbol: "^NDX",
    sourceTag: "Yahoo(Proxy)",
    demoSource: true,
  },
];
